# Generated by Django 4.1.2 on 2022-10-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPage',
            new_name='About',
        ),
    ]
