# Generated by Django 4.1.2 on 2022-10-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_rename_aboutpage_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.AddField(
            model_name='about',
            name='creator_disc',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='about',
            name='creator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='creator_prof',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
