# Generated by Django 4.1.2 on 2022-10-31 09:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_remove_about_name_about_creator_disc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='creator_disc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000),
        ),
    ]
