# Generated by Django 4.1.2 on 2022-10-31 11:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_about_creator_disc_aboutpageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='creator_disc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000),
        ),
    ]
