# Generated by Django 4.1.2 on 2022-11-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_blogindexpage_blogpage_blogpageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blog_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
